# Generated by Django 3.2.6 on 2021-08-31 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_supplier_company_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now=True, verbose_name='date added')),
                ('package_name', models.CharField(max_length=200)),
                ('quantity', models.EmailField(help_text='Required. Inform a valid email address.', max_length=254)),
                ('receipient', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(default='company-name', max_length=200)),
            ],
        ),
    ]
