# Generated by Django 3.2.6 on 2021-08-31 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
